### ISSUE TITLE
`cargo install --git https://github.com/MFEK/metadata` fails due to `fslock` dependency on MacOS 11.6

### ISSUE THREAD

**Issue by eliheuer** [MFEK/metadata#50]
Trying to install MFEKmetadata with `cargo install --git` on MacOS 11.6, I get the following error:
```
福 ~/Solana/repos/mfek/glif2svg ➤ 9aa8d1b|main✓
10844 ± : cargo install --git https://github.com/MFEK/metadata                                                          
    Updating git repository `https://github.com/MFEK/metadata`
  Installing MFEKmetadata v0.0.3-beta1 (https://github.com/MFEK/metadata#6396812b)
    Updating git repository `https://github.com/MFEK/math.rlib`
    Updating crates.io index
    Updating git repository `https://github.com/MFEK/fslock.rlib`
error: failed to compile `MFEKmetadata v0.0.3-beta1 (https://github.com/MFEK/metadata#6396812b)`, intermediate artifacts can be found at `/var/folders/qv/y886wvzj6vl44jb99tqszy680000gn/T/cargo-installxLGwrZ`

Caused by:
  failed to get `fslock` as a dependency of package `MFEKmetadata v0.0.3-beta1 (/Users/eli/.cargo/git/checkouts/metadata-994ea080187c5318/6396812)`

Caused by:
  failed to load source for dependency `fslock`

Caused by:
  Unable to update https://github.com/MFEK/fslock.rlib?branch=preservation

Caused by:
  failed to parse manifest at `/Users/eli/.cargo/git/checkouts/fslock.rlib-bd1a89ca4d1a790e/99718c3/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  duplicate key: `version` for key `package` at line 39 column 1
```

**Comment by ctrlcctrlv** [comment]
Even though I have no way to test on MacOS I believe that ecfe5c9 fixes this due to obvious error in Cargo.toml (_my_ obvious error — ergo my fault), now corrected:

https://github.com/MFEK/metadata/blame/ecfe5c9ea48c886ffb09e6368dea2f20540a2321/Cargo.toml#L15

However, in future, you can avoid such problems by using `--locked`, which would've forced known good versions of all repos to be used, (which is why I never noticed the problem; I hadn't called `cargo update` which resulted in your line above `` Updating git repository `https://github.com/MFEK/fslock.rlib` ``), that is to say, it'll force the commit hashes in `Cargo.lock` even if a newer commit exists in the Git repo.

The reason artifacts still built is equal, because artifacts build `--locked`.

**Comment by eliheuer** [comment]
Thanks! I just tested `cargo install --git https://github.com/MFEK/metadata` on MacOS 11.6, and it worked.
